### ISSUE TITLE
v1.3.1 (MC1.11.2)

### ISSUE THREAD

**Issue by TwitchtvCarbs** [GenDeathrow/MPUtils#11]
Reporting a bug in the game goes to the below link when hitting the 'open in browser' option:

https://minecraft.curseforge.com/projects/mputils/issues

instead of opening the link that is specified in the game from the configuration file.

Copying to clipboard does work, though!

**Comment by GenDeathrow** [comment]
Can I see your config file please? 

so far the code looks right but I may need that file to really test it.

**Comment by TwitchtvCarbs** [comment]
Here is both the basic and MpUtils Config :)

https://pastebin.com/CEfPqz0s

https://pastebin.com/JVdHuBLf

**Comment by GenDeathrow** [comment]
nvm.. I cant believe no one caught this before. Im not even sure how it happened.. putting a fix out now.  well I do I was switching over some code.. and left in some old stuff. but its been like that for a while.

**Comment by TwitchtvCarbs** [comment]
Hey it's no problem! Thank you for being quick on the fix though! :D Really appreciate mod devs that can take the time to respond and fix issues!

**Comment by GenDeathrow** [comment]
its getting reviewed.. it could be 1 min or 5 hours. but its fixed. I realize why no one caught it. It happened when I ported 1.10.2 MC version to 1.11 version

**Comment by GenDeathrow** [comment]
nvm its approved

**Comment by GenDeathrow** [comment]
report back so I know its working as intended please and thank you.

**Comment by TwitchtvCarbs** [comment]
Gen its working like charm now! Thank you my friend :D
