### ISSUE TITLE
Compatibility with Custom Main Menu

### ISSUE THREAD

**Issue by SrAnthony** [GenDeathrow/MPUtils#2]
MPMods are not compatible with CustomMainMenu. The game starts normally, but the button on main screen doesn't appear.
I'm using Minecraft 1.7.10, latest forge for this MC version and latest MPMods version.

**Comment by GenDeathrow** [comment]
Its been on the list to get comparability, but they way they do custom main menu, makes it hard. I will happen at some point.

**Comment by GenDeathrow** [comment]
So with out crazy hacking I cant seem to really add my sliding buttons in. But I'm going to try and set it up to use CMM wrapped buttons to work with MPUtils and not crash the game every time.

**Comment by GenDeathrow** [comment]
https://minecraft.curseforge.com/projects/mputils-basic-tools/pages/mputils-basic-tools/custommainmenu-integration

This is what I can do for now. I fixed the CMM crashing if you used wrapped buttons. Hope this helps
