### ISSUE TITLE
Bug in multiplayer server

### ISSUE THREAD

**Issue by BLICA** [GenDeathrow/MPUtils#22]
When it was supose to grow up a tree when we click shift in single player it grow ups but in multiplayer dont

**Comment by GenDeathrow** [comment]
I think what ever mod pack your using forgot to change the link where you report bugs. What modpack are you using?

**Comment by BLICA** [comment]
Direwolf20

**Comment by GenDeathrow** [comment]
is mputils installed on that? Cause I feel like Im looking at wrong one. I see FTB Presents Direwolf20 1.10

**Comment by BLICA** [comment]
Im sory The modpack is sky factory 3

**Comment by GenDeathrow** [comment]
which version?

**Comment by BLICA** [comment]
Idk but um sure that is The most recent

**Comment by GenDeathrow** [comment]
MPUtils is just a modpack maker tool, used to help display information about a pack to its users. I just downloaded latest version and its pointing to the correct issue tracker. So it sounds like your config files got messed up. Which seems to happen from time to time. Id reinstall the pack. 

Here is the correct issue tracker
https://forum.feed-the-beast.com/forum/ftb-presents-skyfactory-3-1-10.259/
