### ISSUE TITLE
cant turn off JEI/NEI magnet mode

### ISSUE THREAD

**Issue by maryposa1** [GenDeathrow/MPUtils#28]
so when i start a new world i typically will turn magnet mode on through NEI. (only minor cheat i allow myself). but something happend  yesterday and now i find that i am unable to turn it off as the menu option is no longer there.  i dont know if it is a setting i accidently hit  or if it was removed during last update.

any help to get this menu back even temporarily so i can turn it off will be helpfull as it is interfering with some of my botania automations.

 thnx, Maryposa

**Comment by GenDeathrow** [comment]
MPutils is a mod and has nothing to do with the issue. I think your trying to report to a modpack not mputils.
