### ISSUE TITLE
[Crash] - Updating Screen Events on Clicking "Changelog"

### ISSUE THREAD

**Issue by Lanse505** [GenDeathrow/MPUtils#3]
**Intro:**
This might just be me derping up somewhere(Wouldn't suprise me) but I decided to report it anyways:

**Important Mod Versions:**
forge-1.10.2-12.18.2.2124-universal.jar
mpbasic-1.10.2-1.1.0.jar
mputils-1.10.2-1.2.0.jar

**Crashlog:**
https://gist.github.com/Lanse505/25ea24aceff1e3ff978682fa6d213694

**Additional Logs:**
"Changelog.txt": https://gist.github.com/Lanse505/d6850f4616ab764f5dd01f4e26bd7f88
"Mpbasic.cfg": https://gist.github.com/Lanse505/c13e68d62dfaf8f4d0f85019dcc0f3cd

**Comment by GenDeathrow** [comment]
Im on my phone so harder for me t check. Try checking if the change log  file need to be lowercase to match the config settings. If thats the case I may need a fix for that. When I get to my computer I will look into it more

**Comment by GenDeathrow** [comment]
Wait never mind.  Put the url in the config file not. The change log text.

**Comment by GenDeathrow** [comment]
The file address is either a url or a local file.

**Comment by Lanse505** [comment]
Hmm, Sorry for not being able to respond faster.
Due to certain private issues I've had reprioritice.

Anyway:
So I changed it so it looks like this:
http://i.imgur.com/xQg0OCR.png

This however produces this:
http://i.imgur.com/etTXf1U.png

**Comment by Lanse505** [comment]
Another odd bug is this:
http://i.imgur.com/zaHBIIt.png

Takes me to:
http://i.imgur.com/muATShP.png

**Comment by Lanse505** [comment]
not sure why though >->, tbh i'm probably just missing something incredibly obvious and stupid.

**Comment by GenDeathrow** [comment]
For the first one. I know mattabase has done the google docs before, ill ask him what he had done. I bet you have to add something to the https for that to work. The second thing may be an actually bug I need to fix. I bet I messed up with the new issue tracker stuff. I prolly forgot something.

**Comment by GenDeathrow** [comment]
Check here bet this os what you need.

**Comment by GenDeathrow** [comment]
Im on mobile and cant seem to edit my messages... irritating. Here is the link. http://www.labnol.org/internet/direct-links-for-google-drive/28356/

**Comment by Lanse505** [comment]
**Using that link and turning it into a Docx export link produces:**
Adress: https://docs.google.com/document/d/1wojQUho-WLHiyQ1x5ifuvah99FLNolTACfX9pG0XdLE/export?format=doc 

Image: http://i.imgur.com/UANJatn.png

**Using that link and turning it into a PDF export link produces:**
Adress: https://docs.google.com/document/d/1wojQUho-WLHiyQ1x5ifuvah99FLNolTACfX9pG0XdLE/export?format=pdf

Image: http://i.imgur.com/S91ouQR.png

I'll try to talk to Matta and Dark when they pop online again and see if they can provide any input.

**Comment by GenDeathrow** [comment]
Change it to .txt instead. Mputils  .  Only reads plain text files.

**Comment by Lanse505** [comment]
That kinda works to like 99%
Docs:
http://i.imgur.com/rBQW0vN.png

In-Game:
http://i.imgur.com/a3WejNV.png

**Comment by Lanse505** [comment]
Just need to figure out why it's adding the 3 odd symbols before the "1.0.0 - Build 1 - Rebuild 2"

**Comment by Lanse505** [comment]
Yea matta used the same /export?format=txt ending and that works.
However he reports the 3 odd symbols also :P

**Comment by GenDeathrow** [comment]
Its a uni code header for new files. I'm not entirely sure why. I've seen sometimes if you create a new file on notepad it doesn't have the symbols. but I'm prolly going to add in something to remove those uni codes. I could be missing something with the java file reader as well. I will look into though.

**Comment by Lanse505** [comment]
Sounds good 👍

**Comment by GenDeathrow** [comment]
Ok so this is a "UTF-8 BOM". Most text editors will give the option to remove this as it just stats this is utf-8 but apparently google docs doesn't so I might be adding in removing this.

**Comment by Lanse505** [comment]
intressting.

Btw I'm not closing this issue since we've still got the Issue Tracker thing needing to be looked into :P

**Comment by GenDeathrow** [comment]
Ok, I got the first issue fixed, will work on the next one.

**Comment by GenDeathrow** [comment]
Ok that issue has also been fixed..  so we should be good on that as well. Im going to see what else needs some quick work and push this later tonight or tomorrow. Thanks for pointing those out. I really appreciate the help. 

Actually I will leave this open until I actually push the update

**Comment by GenDeathrow** [comment]
New update is up
