### ISSUE TITLE
[Feedback] Stage 0 Feedback

### ISSUE THREAD

**Issue by chiefklondog** [GenDeathrow/MPUtils#30]
Had a change to sit down and play part of stage 0 today and had some feedback/thoughts.

1. [Bug?] Got an iron sword from a drop after killing a tiny Husk/Zombie (Not sure which). Do they have different loot tables?
2. [Feedback] Wolves/Cows seem to run too fast. Even playing local I have some issues with attacks connecting with them and the ability to outplay them. I'm sure on a server that would be painful.
3. [Feedback] Unclear how to use the kiln the first time. I was not aware you could put it over a firepit and spent time putting torches under it as well as trying to light some wood on fire under it. Might just be me being stupid but I am sure others will do the same. :)
4. [Bug?]Tools don't completely break however when using an axe/hatchet on the chopping block they do seem to break
5. [Question] Are bone clubs meant to just be 'better' shovels/picks? They mine both faster right now, even than stone tools. They also don't drop wood when you hit a tree with them however they still break the block super fast.

overall I think this is the most fun in the early game I have ever had with a pack. Keep up the great work! (Also I still can't get over how creepy spiders are with mobends)

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/SevTech-Ages/issues
