### ISSUE TITLE
[Bug] Placing Workstump Mk2

### ISSUE THREAD

**Issue by chiefklondog** [GenDeathrow/MPUtils#31]
Placing workstump Mk2 without having the required levels to use it makes it disappear. If i put an item back in the spot it use to by in my inventory then it appears again

**Comment by chiefklondog** [comment]
Additionally, the fact that I can't place it seems like a bug now that I look. Its saying I need the requirement of "I won't get stumped again" however I do not have that on my advancements page. Not sure what I need to do to unlock it atm either so its just unusable for now with no real explanation.

**Comment by chiefklondog** [comment]
Additionally Additionally, I can't put the workstump mk2 in a chest because it also claims I need that requirement just to place it in the chest. I imagine this will happen with any other place-able items that are blocks by advancements.

**Comment by GenDeathrow** [comment]
hey this is the mod that allows the links to report bugs.. either your config file got overridden or modpack developer forgot to add this too the config file.
