### ISSUE TITLE
[Bug] Getting String

### ISSUE THREAD

**Issue by chiefklondog** [GenDeathrow/MPUtils#32]
There is a recipe for string that is shears + Fleece. This recipe only works with a full durability shears so you can only ever get 1 use out of it.

Additionally, I see recipes for cotton -> string. I spent about 30 min looking for cotton and couldn't find any. Is it just rare? or certain biomes?

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/SevTech-Ages/issues
