### ISSUE TITLE
[Bug] Advancement order - Bark

### ISSUE THREAD

**Issue by chiefklondog** [GenDeathrow/MPUtils#33]
[Bug] In order to unlock the advancement to be able to use a knife to get bark off a tree you need to craft an item (birchbark tome) which requires bark to make.

There are 2 other ways to get back, with a saw and with a stage 1 recipe. Both of these are not possible at this early stage when trying to do the advancement.

[Feedback] The hopper upgrade advancement takes bark to complete however you cannot get bark without completing another advancement in a completely different path that you might not even have uncovered yet.

**Comment by GenDeathrow** [comment]
https://github.com/Darkosto/SevTech-Ages/issues
