### ISSUE TITLE
[Bug] Spriteling drops glowstone

### ISSUE THREAD

**Issue by chiefklondog** [GenDeathrow/MPUtils#34]
The little green flying spritelings drop glowstone in stage 0. And make very annoying bell sounds lol.

**Comment by GenDeathrow** [comment]
hey this is the mod that allows the links to report bugs.. either your config file got overridden or modpack developer forgot to add this too the config file.

**Comment by GenDeathrow** [comment]
Im just guessing,, but I think this is sev tech... https://github.com/Darkosto/SevTech-Ages/issues
