### ISSUE TITLE
[Bug] Direwolves Drops

### ISSUE THREAD

**Issue by chiefklondog** [GenDeathrow/MPUtils#35]
Direwolves do not seem to drop anything wolf relate (pelts/head). I killed about 10 with only bones and meat dropping.

Also, the drop rate for pelts from Steppe wolves seems to be about 1 per but they spawn rarely so its hard to farm them. The drop rate for wolf heads is very close so I ended up with almost as many wolf heads as I did pelts after farming for them.

**Comment by GenDeathrow** [comment]
hey this is the mod that allows the links to report bugs.. either your config file got overridden or modpack developer forgot to add this too the config file.

**Comment by chiefklondog** [comment]
well now I feel like an idiot :(
And yes it was the auto link from the pause menu.

**Comment by chiefklondog** [comment]
Do you want me to put new bugs in on the Sev Tech page you linked?

**Comment by GenDeathrow** [comment]
yeah cause this mod if for modpacks, it doesn't have anything to do with the pack it self. I'm guessing this is the sev tech modpack.

**Comment by chiefklondog** [comment]
Thanks, I apologize for the hassle of my mistake! :)

**Comment by GenDeathrow** [comment]
dont worry about it.. it happens all the time
