### ISSUE TITLE
Item dublicate 

### ISSUE THREAD

**Issue by TotalyFine** [GenDeathrow/MPUtils#37]
dupes when full inventory. https://youtu.be/QAW6OhavRlQ

**Comment by GenDeathrow** [comment]
For some reason I think your mputils configs didn't get properly copied over from the sev tech pack download. Mputils is what gives you the link to github, and should be pointing else where. 

https://github.com/Darkosto/SevTech-Ages/issues

But Id make sure all your configs are all correct. but that is a pretty bad bug there you found.
