### ISSUE TITLE
[BETA 1] Mekanism Salt doesn't trigger the advencement reSalt of your Labor

### ISSUE THREAD

**Issue by Fireztonez** [GenDeathrow/MPUtils#40]
Hello Darkosto,
I think everithing is clear in the Title,
I try the Beta 1, start a new game and start trhe advencement, and for the salt, I try with the Salt of Mekanism in the river and doesn't trigger the advencement... Probably you should turn off that generation or make it work woith your advencement...

Fireztonez!

**Comment by GenDeathrow** [comment]
Ok now Im thinking that you didn't get all the config files some how. Because I know darks pack has correct links.
