### ISSUE TITLE
[Beta 1][Enhancement] Add Coffee from Actually Addition recipe to Brown Dye powder

### ISSUE THREAD

**Issue by Fireztonez** [GenDeathrow/MPUtils#41]
I think the coffee should be a good thing to be added for recipes for make a brown dye... The coffee is easy to find, and is logically work for make a dye i think....

**Comment by GenDeathrow** [comment]
Wrong place either you didn't get all the config files for your modpack or they forgot to link to the correct github. this is the mod that alllows modpack makers to link reporting.
