### ISSUE TITLE
Forever Stranded Hurt Edition 1.0.3

### ISSUE THREAD

**Issue by Nikita1994ss** [GenDeathrow/MPUtils#45]
I have no idea where to report it. The link has come to this page. I hope the mod designer will read this
If anything does not hit with your feet )

This is about  Forever Stranded Hurt Edition 1.0.3

The quest should be done "wooden_hummer" but it turns out "wooden_wrench" and the quest can not be completed. :(

ps:And also there is no way to heal no effect from food and potions

**Comment by GenDeathrow** [comment]
Apparently your download of the mod pack messed up cause this is the page for the mod that allow's you to report bugs. Not the mod pack for forever stranded. This seems to happen every so often and you may not have all the configs correctly downloaded.. I would re-download your mod pack.  Either way Im closing this cause I have nothing to do with that modpack.
