### ISSUE TITLE
Crash on login to world when in creative

### ISSUE THREAD

**Issue by justinrusso** [GenDeathrow/MPUtils#48]
I am prompted with the Getting Started screen when joining the world. When I click the "Close" button I crash with a StackOverflow.

Log: https://pastebin.com/BcwY8MgS

#### Versions
Minecraft: 1.12.2
Forge: 14.23.5.2775
MPUtils: 1.5.6

**Comment by justinrusso** [comment]
Seems to be happening in more than just creative as well. I suppose every time a GUI is open when it also opens the screen maybe?

**Comment by GenDeathrow** [comment]
Strange.. I am working my way thur my mods atm.. since I have been on a bit of a hiatus. I take a look at it as son as I can

**Comment by GenDeathrow** [comment]
should have been fixed with latest version released today (1.5.6v)
