### ISSUE TITLE
Grains of infinity

### ISSUE THREAD

**Issue by zac1228** [GenDeathrow/MPUtils#50]
I don't know if its expected or not but, you can buy Grains of infinity from the shop. It cost 50 coins to buy Grains of infinity. If you put the Grains of infinity in the the Transmutation table, you get 16,386 EMC. Seems a bit OP. I understand that thats the point of the pack, but that just seems to stand out a bit too much for early game lol

**Comment by GenDeathrow** [comment]
This is MPutils mod and not the modpack you are looking for. Something may have happened with with your download.
