### ISSUE TITLE
Questbook ChosenArchitech

### ISSUE THREAD

**Issue by dj2599** [GenDeathrow/MPUtils#52]
Started playing on ChosenArchitech's world and it starts you with Dark Oak Wood and the quest book asks for regular Oak.

**Comment by GenDeathrow** [comment]
This is MPutils mod and not the modpack you are looking for. Something may have happened with with your download. or they forgot to put in the correct link in the mputils mod.

**Comment by dj2599** [comment]
Oh my mistake I was under the impression that the link brought me a bug page for the modpack.

**Comment by GenDeathrow** [comment]
It should I think they forgot to change the default lol. I get a report to them.

**Comment by GenDeathrow** [comment]
https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/
