### ISSUE TITLE
[Bug] Botania + Better Builders Wand

### ISSUE THREAD

**Issue by mesbozi** [GenDeathrow/MPUtils#57]
When using the Better Builder Wands on the Botania endoflame, the endoflames were not placed and were instead replaced by a no texture flower. When I used the '/wandOops' command the flowers that were sent back to my inventory were the 'botania flower'. I assume that this will happen with all wands and all flowers because it happens every time

**Comment by GenDeathrow** [comment]
They are linking to the default for mputils.. here is the actual issue tracker.
https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/
