### ISSUE TITLE
cant burn items at high emc

### ISSUE THREAD

**Issue by awesomebender** [GenDeathrow/MPUtils#59]
I found that when I started having lots of emc in the transmutation table starting at about 100,000,000,000,000,000,000,000 emc or 1E emc the table would no longer burn items that I would be able to burn before but you can still take out as items as normal and can still teach the table normally If it helps I an using a transmutation tablet and I have several hundred of the final power flower bonsai thanks in advance

**Comment by awesomebender** [comment]
sorry wrong page ftb odyssey linked me to this page for bugs

**Comment by GenDeathrow** [comment]
yeah they forgot to put the correct link in.. they have it fixed on the next update.
