### ISSUE TITLE
AE2 wireless infinity booster cards

### ISSUE THREAD

**Issue by GenesisXBD** [GenDeathrow/MPUtils#62]
not a bug but why have these when you cannot use them or the crafting terminal that the mod provides?

**Comment by GenDeathrow** [comment]
This is the mputils mod, the link to the modpack your looking for is wrong.  This mod helps pack developers send ppl to correct place.  If this is for the FTB Odyssey modpack, than they have fixed this.. but wont be till next update. 

here is there issue tracker. 
https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/
