### ISSUE TITLE
Unplayable

### ISSUE THREAD

**Issue by alper5ozx** [GenDeathrow/MPUtils#63]
[bug.zip](https://github.com/GenDeathrow/MPUtils/files/3025308/bug.zip)

Everytime I move the screen shakes and its making the game unplayable

**Comment by GenDeathrow** [comment]
Stop moving.

**Comment by GenDeathrow** [comment]
also for a bug report better to put it into a gist or pastebin. Also I have a template that you should have read and followed before deleting and writing what you did.

**Comment by GenDeathrow** [comment]
And This is a mod not the modpack your playing.  

More than likely your playing Odyssey. Your prolly meaning to report there.

here is there issue tracker.
https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/
