### ISSUE TITLE
Dupping using advanced item collectors

### ISSUE THREAD

**Issue by Superkid700** [GenDeathrow/MPUtils#65]
Note: This issue tracker is for MPUtils mod, if you were looking for a a certain mod pack. Than the pack developer forgot to link to the correct Url for it. Please find there issue tracker and inform them. Thank you.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### Steps to reproduce (important):

1. Open Advanced Item Collector
2. Shift Click Any Item
3. Doubles Stack
...

#### What you expected to happen:

____
#### Affected Versions (Do *not* use "latest"):

- MPUtils Mods: 
- Minecraft: 
- Forge:

**Comment by GenDeathrow** [comment]
Question, did you read the top notes of your bug report? I'm pretty sure your meaning to report else where.The pack developer forgot to change the in game link, and your pointing to the wrong location. Mputils is what gives the functionality to have the ingame link to issue tracker.
