### ISSUE TITLE
mobs won't spawn 

### ISSUE THREAD

**Issue by xTheHellGamesx** [GenDeathrow/MPUtils#66]
Note: This issue tracker is for MPUtils mod, if you were looking for a a certain mod pack. Than the pack developer forgot to link to the correct Url for it. Please find there issue tracker and inform them. Thank you.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### Steps to reproduce (important):

1. 
2. 
3. 
...

#### What happens:

mobs won't spawn when i create a mob spawner

#### What you expected to happen:

mobs to spawn
____
#### Affected Versions (Do *not* use "latest"):

- MPUtils Mods: 
- Minecraft: 
- Forge:

**Comment by GenDeathrow** [comment]
Question, did you read the top notes of your bug report? I'm pretty sure your meaning to report else where.The pack developer forgot to change the in game link, and your pointing to the wrong location.  Mputils is what gives the functionality to have the ingame link to issue tracker.
