### ISSUE TITLE
Data Module deletes from Simulation Chamber after using Yeta Wrench.

### ISSUE THREAD

**Issue by Edison1121** [GenDeathrow/MPUtils#68]
I attached an Item Conduit (Ender I/O) to the bottom of a Simulation Chamber (Deep Mob Learning) and right clicked with a Yeta Wrench (Ender I/O) on the conduit.  It caused the current Data Module (Deep Mob Learning) that was in the chamber to disappear/delete.

- Minecraft: 1.12.2
- Forge: 14.23.5.2815

**Comment by GenDeathrow** [comment]
please contact the modpack please. You may have the incorrect link.
