### ISSUE TITLE
Can't launch Minecraft when MPUtils is installed

### ISSUE THREAD

**Issue by AlexandraIsabel** [GenDeathrow/MPUtils#71]
#### Issue Description:
Unable to launch ANY pack with MPUtils included.

#### Steps to reproduce (important):
Launch the game and wait till it gets to "Mod Initialization Phase 2".

#### What happens:
The game crashes (I will attach the crash report).

#### What you expected to happen:
The game continues to load to the title screen.

____
#### Affected Versions (Do *not* use "latest"):

- MPUtils Mods: MPUtils 1.5.7 and MPBasic 1.4.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
[crash-2019-11-29_07.59.28-client.txt](https://github.com/GenDeathrow/MPUtils/files/3905277/crash-2019-11-29_07.59.28-client.txt)

**Comment by AlexandraIsabel** [comment]
I was able to resolve this on my own. Looks like the `.mputils` directory under my user profile wasn't accessible.

**Comment by GenDeathrow** [comment]
Sorry meant to get back to you sooner.. TBH I thought I had a check to ignore the directory if it wasn't accessible. But since you you brought this up.. I will have to remember to put a check in now. Thanks
