### ISSUE TITLE
Email Error

### ISSUE THREAD

**Issue by pat0603** [GenDeathrow/MPUtils#8]
I am using google sheets for my data and there is one error, the email is phrased wrong. It is set as `=HYPERLINK(mailto:USERS EMAIL", "USERS EMAIL")` when it should be `=HYPERLINK(mailto:"USERS EMAIL", "USERS EMAIL")` it is missing the quotation mark after the mailto:

Here is my config file:
[http://pastebin.com/fAwZXsTQ](http://pastebin.com/fAwZXsTQ)

**Comment by GenDeathrow** [comment]
didnt realize that.. thats going to be inside your google script. you should be able to fix that. I just updated it on my side..

https://gist.github.com/GenDeathrow/15c2f103fa3ad3a222bbf8ff756a5e69#file-gistfile1-txt-L74
